### PR TITLE
Add Donovan Dikaio, Entrepreneur

### PR DESCRIPTION
**Pull request by dikaio**
If you are signing, please put your FULL NAME in the TITLE OF THE PULL REQUEST.

You should have a file called your-name.yml in /_data/supporting, with the following keys:

* `sortName`: Your family name (just for sorting, not displayed, not case sensitive)
* `displayName`: How your full name should be displayed.  Please capitalise if appropriate to your language.
* `url`: URL of your website, profile or AMP-related statement

### CODE REVIEW

**Comment by triblondon** [comment]
This is a very minimal website.  Do you have anything more substantive - linkedin, twitter something like that?

**Comment by dikaio** [comment]
😃 Hi @triblondon. Here's my [Twitter profile](https://twitter.com/dondikaio?lang=en) and [LinkedIn profile](https://www.linkedin.com/in/dondikaio/).

**Comment by triblondon** [comment]
Yep, either of those is fine

**Comment by dikaio** [comment]
Ahhh.. I misunderstood, pushing now!

**Pull request merged**
