### PR TITLE
Create Matt Holovach

### PR DESCRIPTION
**Pull request by seoMattH**
I find what Google is doing with AMP to be very disappointing especially for a company that has a mantra of do no evil.

If you are signing, please put your FULL NAME in the TITLE OF THE PULL REQUEST.

You should have a file called your-name.yml in /_data/supporting, with the following keys:

* `sortName`: Your family name (just for sorting, not displayed, not case sensitive)
* `displayName`: How your full name should be displayed.  Please capitalise if appropriate to your language.
* `url`: URL of your website, profile or AMP-related statement

### CODE REVIEW

**Comment by jed** [comment]
@seoMattH, please use a personal URL, not a company.

**Comment by seoMattH** [comment]
I don't have a personal URL and I don't use social media.  I wanted to try and add my company page, but I was told that my company was too small.  Can I just add the company name to the Organization section?  

I really want to add my support to this open letter, because Amp forces a bunch of extra development time for my team otherwise my clients get penalized for not having AMP versions of there site.  Not to mention I don't like that Google's near monopoly power on search forces us to do whatever they require.  Please advise.

**Comment by triblondon** [comment]
Hey Matt,

When it comes to showing genuine support for the letter, we need to have the backup of something that represents the signatory and tells the reader something about who they are, otherwise we could be making all thheee signatures up. Organisational signatories are really for substantial organisations.

If you don’t have a twitter, LinkedIn or Facebook profile, nor a personal website or blog, I guess you could link to your github profile. Or if there’s a page specifically about you on your company site, you could link to that.

**Comment by seoMattH** [comment]
Ok then can I write a blog post about why AMP irritates the shit out of me?  Then link to that on the business site?  It will show that I'm the author.

**Comment by triblondon** [comment]
Sure, that’s fine.

**Comment by seoMattH** [comment]
I have changed the URL to a blog post discussing AMP.  Hopefully this will suffice.  Thanks

**Comment by triblondon** [comment]
Perfect, thanks for bearing with us.

**Pull request merged**
