### PR TITLE
Add my name

### PR DESCRIPTION
**Pull request by hidde**
Hello! I'd like to show my support and sign this please.

### CODE REVIEW

**Comment by triblondon** [comment]
This doesn't seem like the right spot for your name alphabetically.  Could you take a look at that?

**Comment by hidde** [comment]
@triblondon Ah, it's my language I think :-) In Dutch, “Vries” is the last name and first word in uppercase, “de” is just a word that goes in between (in a Dutch list, the surname  “de Vries” it would go between U an W). Happy to move it to D if that would suit better in this case.

**Comment by hidde** [comment]
(Have resolved conflict)

**Comment by triblondon** [comment]
Due to the volume of pull requests on this repository, we have extracted all the signatories and combined them into the following single commit:

https://github.com/amp-letter/amp-letter.github.io/commit/9d631e2d57e2b4ce80c87874b03029d341cb2b7f

The sorting has been done based on the final word of your name.  We know that this is not a foolproof way of sorting names, and if your name is not correctly sorted, please feel free to raise a PR to fix it.

**Pull request merged**
