### PR TITLE
Add Raphael Gauvain

### PR DESCRIPTION
**Pull request by lestote**
💯

### CODE REVIEW

**Comment by triblondon** [comment]
Web address invalid.  Corrected web address results in 403 forbidden error.

**Comment by lestote** [comment]
@triblondon Oups ! It's fixed now, sorry this page is a WIP.

**Comment by triblondon** [comment]
Still invalid, though the destination site now works.

**Comment by lestote** [comment]
Hi, oh i see i missed a typo. Sorry about that.

**Pull request merged**
