### PR TITLE
add NZZ Storytelling

### PR DESCRIPTION
**Pull request by benib**

### CODE REVIEW

**Comment by davidbauer** [comment]
Just to clarify: I'm fine with being added.

**Comment by zachleat** [comment]
Hey Beni and David, our current stance is that we’d like organizations to link to their canonical home page. Can you update the URL? Then we can merge

**Comment by benib** [comment]
@zachleat alright. this PR got messed up until now with trying to resolve conflicts with the github webinterface. will send a clean one.

**Comment by benib** [comment]
new clean PR: https://github.com/amp-letter/amp-letter.github.io/pull/575

**Pull request closed without merging**
