### PR TITLE
Add I Programmer

### PR DESCRIPTION
**Pull request by Drmikej**
If you are signing, please:

* Include your full name in the TITLE of the PR
* Place your name in the list ALPHABETICALLY by FAMILY name
* Check your PR after you create it to ensure that you didn't accidentally delete other signatories while editing the file.  While you are editing, other PRs may be merged.

### CODE REVIEW

**Comment by Drmikej** [comment]
Hi 
I Programmer would like to run a news item on this but if an interested publication like I Programmer cannot sign the letter I don't think there is scope for a news item. 
After all I Programmer considered and rejected using AMP - for us this isn't theory.
PS I'm the editor

**Comment by zachleat** [comment]
Hey Mike, I get security warnings on your website. Can you change the link to use `http` instead?

**Comment by Drmikej** [comment]
Think I've updated it now. 
The https was a mistake.

**Comment by triblondon** [comment]
To resolve a huge number of conflicts and make it easier to ensure valid markup, we are moving to a Jekyll generated site using YAML data files.  Sorry this causes you the inconvenience of having to submit again, but it shouldn't be too hard and you can be sure of not conflicting!

To view the new instructions, see https://github.com/amp-letter/amp-letter.github.io/blob/master/README.md

**Pull request closed without merging**
