### PR TITLE
Matt Holovach

### PR DESCRIPTION
**Pull request by seoMattH**
sortName: Holovach
displayName: Matt Holovach
url: https://www.coloradoseodesign.com/

### CODE REVIEW

**Comment by triblondon** [comment]
This PR has captured a huge amount of changes.  I think you will need to rebase it at a minimum.  However, what we've been saying to very small organisations, is it's probably better to sign as individuals.

**Comment by seoMattH** [comment]
I can sign as an individual but I don't utilize social media so I will still need to link to my website.  I also don't understand what "This PR has captured a huge amount of changes" means.  Sorry for my ignorance but I'm a git newbie.  Google is trying to force our web development into AMP and it really frustrates me so I want to be on this open letter either individually or as a business.

**Comment by triblondon** [comment]
I'm not sure how you've done it either!  But if you click "Changes" you'll see your proposed edit affects 550 files.  I think you should probably try and start again - just use the Github web UI, that's normally the easiest way.  Instructions are in the README at https://github.com/amp-letter/amp-letter.github.io/blob/master/README.md.

Your personal website will be fine.  If you only have a business website, and you don't have anything like a linkedin profile or any social profile or anything, then we are a bit stuck.

**Comment by seoMattH** [comment]
I don't utilize a personal website, my business is pretty much my personal life.  I've gone into supporting and tried to add a file utilizing the web UI so hopefully I did it right.  Thanks for the help

**Comment by seoMattH** [comment]
I think I figured it out sorry for the confusion.

**Pull request closed without merging**
