### PR TITLE
Vietnamese

### PR DESCRIPTION
**Pull request by dnhn**
Happy to provide the Vietnamese translation of the letter!

### CODE REVIEW

**Comment by triblondon** [comment]
Thanks! Can you find another couple of native speakers to review this translation?

**Comment by dnhn** [comment]
@nhutdm @vinhnx @trungk18
Dear fellow developers, could you help me review this Vietnamese translation?

**Comment by vinhnx** [comment]
LGTM! 👍

**Comment by nhutdm** [comment]
It looks good to me too! 👍

**Comment by trungvose** [comment]
It looks good to me.

**Comment by dnhn** [comment]
Thank you @vinhnx @nhutdm @trungk18 👏👏👏
@triblondon I guess this is good to go now.

**Comment by triblondon** [comment]
Thank you!  And amazingly good job to get the translation perfect on the first try.

**Pull request merged**
