### PR TITLE
Luther Lowe

### PR DESCRIPTION
**Pull request by phamann**
Add Luther Lowe as cosignatory, they don't have GitHub and requested via email.

### CODE REVIEW

**Comment by triblondon** [comment]
Hey @phamann could you ask Luther to tweet their consent publicly, and fix the couple of names that got deleted in your edit?

**Comment by phamann** [comment]
@triblondon I have fixed conflicts. Luther will tweet consent :)

**Comment by triblondon** [comment]
@phamann I see the tweets.  Sorry for the delay - could you resubmit to clear the conflicts again (sorry!)

**Comment by triblondon** [comment]
Oh actually ignore - I captured Luther in a bulk update.

**Pull request closed without merging**
