### PR TITLE
Add Jordan Warren as signatory

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@triblondon https://techwanderers.com/amp-letter.github.io.txt

**Comment by triblondon** [comment]
Hey Jordan,

Sorry for the mysterious lack of feedback there.  My concern was mostly that your site doesn't describe you, it's more a company presence. Could you link to a post you've personally written about AMP? Or perhaps your personal site / twitter profile?

**Comment by ghost** [comment]
@triblondon 

No problem!

I've changed the URL to my Twitter profile. Sadly it's just as vague; hopefully that isn't an issue.

**Comment by triblondon** [comment]
It'll do :-)

**Pull request merged**
